### ISSUE TITLE
Transparent grouped sub menu

### ISSUE THREAD

**Issue by camexapps** [Rhym/silverstripe-cms-theme#15]
Hi Ya,

Loving the new v1 update (very clean). I just noticed when in SS 3.5.X (not sure about earlier ones) whilst using the Grouped Menu (silverstripe-grouped-cms-menu) system. When editing a page, it forces the side menu to collapse. The problem is, when trying to hover over a grouped menu item, the background is transparent, which can make it rather difficult as there can be sub menu items that the client may want to access.

Screen shot below for clarification (ignore the  pixellated page names)

![test](https://cloud.githubusercontent.com/assets/1858524/23978034/95472e88-0a56-11e7-996b-ad24be0ceccb.png)
:

**Comment by camexapps** [comment]
Adding to this..

It looks like the 'collapsed' menu also removes your custom CSS of the following:

```css
.cms-menu .cms-menu-list li.children .grouped-cms-menu:after
```

So, the 'icon(s)' you have setup for the grouped areas are removed.

Thinking out loud here, but the **silverstripe-grouped-cms-menu** system comes built in with the ability to specific the icon for the group(s), which when used, adds the prefix of 'icon-' apparently:

```yaml
LeftAndMain:
  menu_groups:
    Content:
      icon: 'cmspagescontroller'
      - CMSPagesController
      - AssetAdmin
```

So theoretically could we look at doing such as:

```yaml
LeftAndMain:
  menu_groups:
    Content:
      icon: ' fa fa-file-text-o'
      - CMSPagesController
      - AssetAdmin
```

Have not yet tested this...

**Comment by Rhym** [comment]
Damn collapsible menu. I actually made it so that shouldn't show, but I guess something is being overwritten. I'll take a look now.

**Comment by Rhym** [comment]
@camexapps Give it a go now.

**Comment by camexapps** [comment]
Exellent, the only issue is if there is a logo. It seems to get cut off a bit. I did see this bit of the admin CSS that just needs to be overwritten:

```css
.cms-menu.collapsed .cms-logo {
    height: 28px;
    padding: 12px 0 11px;
}
```

Should become something like?

```css
.cms-menu.collapsed .cms-logo {
    height: auto;
    padding: 12px 0 11px;
}
```
